# Site settings
title:          Paying My Rent
description:    "My journey through self-improvement"
url:            "https://payingmyrent.com"

# Google Analytics
google_analytics: UA-157021582-3

# Author
author:
  name:         Parav Singla
  url:          https://paravsingla.com
  email:        hello@paravsingla.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:title
paginate:       6

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
#disqus:         jekyll-tale
